name: onetep tutorials

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  tutorials-builds:
    runs-on: ubuntu-latest
    container: sphinxdoc/sphinx-latexpdf:5.3.0
    steps:
    - uses: actions/checkout@v4
    - name: sphinx
      run: |
        pip install sphinx-rtd-dark-mode
        pip install sphinx-favicon
        make latexpdf
        cp build/latex/oneteptutorials.pdf  source/_static/
        make html

  tutorials-deploy:
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    container: sphinxdoc/sphinx-latexpdf:5.3.0

    steps:
    - uses: actions/checkout@v4
    - name: sphinx
      run: |
        pip install sphinx-rtd-dark-mode
        pip install sphinx-favicon
        make latexpdf
        cp build/latex/oneteptutorials.pdf  source/_static/
        make html
    - name: upload
      uses: actions/upload-pages-artifact@v3
      with:
        # Upload entire repository
        path: './build/html/.'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

